[package]
name = "cw721-stake"
version = "0.1.0"
authors = ["CypherApe cypherape@protonmail.com"]
edition = "2018"
license = "Apache-2.0"
repository = "https://github.com/DA0-DA0/dao-contracts"
description = "CW721 token that can be staked and staked balance can be queried at any height"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
backtraces = ["cosmwasm-std/backtraces"]
# use library feature to disable all instantiate/execute/query exports
library = []

[dependencies]
cosmwasm-std = { version = "1.0.0" }
cosmwasm-storage = { version = "1.0.0" }
cw-storage-plus = { version = "0.13" }
cw-controllers = "0.13"
cw721-controllers = { version = "0.1.0", path = "../../packages/cw721-controllers" }
cw20 = { version = "0.13" }
cw721 = { version = "0.13" }
cw-utils = { version = "0.13" }
cw721-base = "0.13"
cw2 = "0.13"
schemars = "0.8.8"
serde = { version = "1.0.132", default-features = false, features = ["derive"] }
thiserror = { version = "1.0.30" }
cw20-base = {  version = "0.13", features = ["library"] }

[dev-dependencies]
cosmwasm-schema = { version = "1.0.0" }
cw-multi-test = {  version = "0.13" }
anyhow = { version = "1.0.51"}
